name: taller_trips
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Dosis
      fonts:
        - asset: assets/fonts/Dosis-Regular.ttf
        - asset: assets/fonts/Dosis-Light.ttf
        - asset: assets/fonts/Dosis-Bold.ttf
  
  assets:
    - assets/images/luffy.jpg